source /usr/share/zsh/share/antigen.zsh

antigen bundle robbyrussell/oh-my-zsh /lib

antigen bundle git
antigen bundle pip
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship

antigen apply

#HISTFILE=~/.zsh_history
#SAVEHIST=1000
ZSH_AUTOSUGGEST_USE_ASYNC=true
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

alias ls='ls --color=auto'
alias cd..='cd ..'

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export VISUAL=vim
export EDITOR=vim

PATH="$HOME/.node_modules/bin:$PATH"

