[font]
normal = { family = "IBM Plex Mono", style="Regular" }
size = 13

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
