case `uname` in
    Darwin)
        source /usr/local/share/antigen/antigen.zsh
    ;;
    Linux)
        source /usr/share/zsh/share/antigen.zsh
        alias ls='ls --color=auto'
    ;;
esac

antigen bundle robbyrussell/oh-my-zsh /lib

antigen bundle git
antigen bundle pip
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme https://github.com/romkatv/powerlevel10k powerlevel10k

antigen apply

#powerlevel10k configuration stuff
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH_AUTOSUGGEST_USE_ASYNC=true
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

#fzf config
case `uname` in
    Linux)
        source /usr/share/fzf/key-bindings.zsh
        source /usr/share/fzf/completion.zsh
    ;;
    Darwin)
        source /usr/local/opt/fzf/shell/key-bindings.zsh
        source /usr/local/opt/fzf/shell/completion.zsh
    ;;
esac
export FZF_DEFAULT_COMMAND='fd --type f'
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

alias cd..='cd ..'

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
  -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
  -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export VISUAL=vim
export EDITOR=vim
export GEM_HOME=$HOME/.gem

PATH="$HOME/.node_modules/bin:$PATH"
PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"

### predator specific configuration

if [[ $(hostname) == 'avprdtr' ]]; then
  export VDPAU_DRIVER='nvidia';
fi

### work stuff

CAFETO_VAULT=~/Vaults/CafetoSoftware
PROS_BOOTSTRAP=$CAFETO_VAULT/PROS/.prosrc
if [ -f $PROS_BOOTSTRAP ]; then
    source $PROS_BOOTSTRAP
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

