source /usr/share/zsh/share/antigen.zsh

antigen bundle robbyrussell/oh-my-zsh /lib

antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle micha/resty

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme https://github.com/romkatv/powerlevel10k powerlevel10k
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

antigen apply

ZSH_AUTOSUGGEST_USE_ASYNC=true
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

#fzf config
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP

alias ls='ls --color=auto'
alias cd..='cd ..'

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export VISUAL=vim
export EDITOR=vim
export GEM_HOME=$HOME/.gem

PATH="$HOME/.node_modules/bin:$PATH"
PATH="$HOME/.gem/ruby/2.6.0/bin:$PATH"
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"

CAFETO_VAULT=~/Vaults/CafetoSoftware
PROS_BOOTSTRAP=$CAFETO_VAULT/PROS/.prosrc
if [ -f $PROS_BOOTSTRAP ]; then
    source $PROS_BOOTSTRAP
fi
